# SPDX-FileCopyrightText: 2024 NULL882 <gost6865@yandex.ru>
# SPDX-FileCopyrightText: 2024 gluesniffler <159397573+gluesniffler@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  id: BaseMechWeaponMelee
  parent: BaseMechEquipment
  abstract: true
  components:
  - type: Appearance
  - type: StaticPrice
    price: 1
  - type: Item
    size: Ginormous
  - type: MultiHandedItem
  - type: ClothingSpeedModifier
    walkModifier: 0.80
    sprintModifier: 0.80
  - type: HeldSpeedModifier
    mirrorClothingModifier: false
    walkModifier: 0.75
    sprintModifier: 0.75
  - type: HeldSpeedModifier
  - type: UpgradeableGun
    maxUpgradeCapacity: 50
    whitelist:
      tags:
      - WeaponUpgradeMech
  - type: Clothing
    slots: BACK, SUITSTORAGE
